### ISSUE TITLE
LInk to self

### ISSUE THREAD

**Issue by avianmanagement** [clientIO/JointJS_plus#9]
In a ERD it's possible to have a relation from an entity back into itself.

I have been able to do it in the DAGRE example, but the arrow is shown really small within the entity rather then coming out of it and then looping back in.

Is it possible to have a link shown back into itself so that one can see it.

**Comment by DavidDurman** [comment]
That could be done programmatically by listening on `source`/`target` changes on the graph, detecting whether the link is a 'self-loop' and setting `vertices` on such a link so that the link is going out of the element and looping back.

``` javascript
graph.on('change:source change:target', function(link) {
   if (link.get('source').id === link.get('target').id) {
       // self-looping link detected.
       link.set('vertices', findLoopLinkVertices(link));
   }
})
```

Where `findLoopLinkVertices(link)` is a function that returns an array of vertices so that the link is drawn as a self-loop. This function is basically implemented in `joint.ui.Halo.js >> makeLoopLink(link)` but might need to be a little bit adjusted.

**Comment by avianmanagement** [comment]
Thank you very much

I'll see what I can do with this, Javascript is very new to me, but the more I play with it the more I am amazed how powerful it is.

David Le Mesurier
